theme: jekyll-theme-minimal
title: Electronic Detector Group @BNL
logo: _logo/edg.png
description: 
show_downloads: false
people: https://www.phy.bnl.gov/edg/w/List_of_EDG_Members
news: https://www.phy.bnl.gov/edg/w/News


