url: https://www.phy.bnl.gov
baseurl: /edg
theme: jekyll-theme-minimal
title: Electronic Detector Group @BNL
logo: assets/images/logo/edg.png
description: 
show_downloads: false
people: https://www.phy.bnl.gov/edg/w/List_of_EDG_Members
news: https://www.phy.bnl.gov/edg/w/News
publications: https://docs.google.com/document/d/e/2PACX-1vQlFYyLXDoIAqKokFuQy13LO6yGX4Z6SPU2EUjBf7zS3YsMB9gDasYznWaKW59DW5bK4NfW6ZqdnACx/pub

